-include .env

VERSION ?= $(shell git rev-parse --short HEAD)

VERSION_DISTRIBUTE = $(VERSION_DISTRIBUTE)
VERSION_WATCHER = $(VERSION_WATCHER)

DEV_EOS_API_ENDPOINT = $(DEV_EOS_API_ENDPOINT)
DEV_EOS_API_CHAIN_ID = $(DEV_EOS_API_CHAIN_ID)
DEV_EOS_DISTRIBUTE_ACCOUNT = $(DEV_EOS_DISTRIBUTE_ACCOUNT)
DEV_EOS_DISTRIBUTE_PERMISSION = $(DEV_EOS_DISTRIBUTE_PERMISSION)
DEV_EOS_DISTRIBUTE_PRIVATE_KEY = $(DEV_EOS_DISTRIBUTE_PRIVATE_KEY)
DEV_EOS_DISTRIBUTE_MAX_STEPS = $(DEV_EOS_DISTRIBUTE_MAX_STEPS)
DEV_EOS_EDEN_ACCOUNT = $(DEV_EOS_EDEN_ACCOUNT)
DEV_EOS_PAYER_ACCOUNT = $(DEV_EOS_PAYER_ACCOUNT)
DEV_EOS_PAYER_PERMISION = $(DEV_EOS_PAYER_PERMISION)
DEV_EOS_WATCH_ACCOUNT = $(DEV_EOS_WATCH_ACCOUNT)
DEV_EOS_POWERUP_THRESHOLD = $(DEV_EOS_POWERUP_THRESHOLD)
DEV_EOS_NET_FRAC = $(DEV_EOS_NET_FRAC)
DEV_EOS_CPU_FRAC = $(DEV_EOS_CPU_FRAC)
DEV_EOS_POWERUP_AMOUNT = $(DEV_EOS_POWERUP_AMOUNT)

MAKE_ENV += VERSION VERSION_DISTRIBUTE VERSION_WATCHER DEV_EOS_API_ENDPOINT DEV_EOS_API_CHAIN_ID DEV_EOS_DISTRIBUTE_ACCOUNT DEV_EOS_DISTRIBUTE_PERMISSION DEV_EOS_DISTRIBUTE_PRIVATE_KEY DEV_EOS_DISTRIBUTE_MAX_STEPS DEV_EOS_EDEN_ACCOUNT DEV_EOS_PAYER_ACCOUNT DEV_EOS_PAYER_PERMISION DEV_EOS_WATCH_ACCOUNT DEV_EOS_POWERUP_THRESHOLD DEV_EOS_NET_FRAC DEV_EOS_CPU_FRAC DEV_EOS_POWERUP_AMOUNT

SHELL_EXPORT := $(foreach v,$(MAKE_ENV),$(v)='$($(v))')

ifneq ("$(wildcard .env)", "")
	export $(shell sed 's/=.*//' .env)
endif